### ISSUE TITLE
[Visual][navbar] Social media icons + padding 

### ISSUE THREAD

**Issue by shamchittesh** [mscraftsman/devcon2024#4]
Twitter icon black compared to others being in white; 
<img width="188" alt="Screenshot 2024-03-29 at 21 01 46" src="https://github.com/mscraftsman/devcon2024/assets/36814895/41883647-b784-4bb9-abe5-5bf431807884">

No paddings on the sides for the banner, the button gets overlapped with the scrollbar
<img width="249" alt="Screenshot 2024-03-29 at 21 09 40" src="https://github.com/mscraftsman/devcon2024/assets/36814895/9e4a1fa8-12d1-4b9a-9b50-e81fb67938c5">

**Comment by shamchittesh** [comment]
PR created: https://github.com/mscraftsman/devcon2024/pull/5

**Comment by jochenkirstaetter** [comment]
Thanks, merged.
